name: Github JDSign-in bot

on: # 触发条件
    push:
        branches:
            - main
    workflow_dispatch: # 手动触发
    schedule:
        - cron: '15 16 * * *' # beijing时间 0:15
jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout codes
              uses: actions/checkout@v2
              with:
                  ref: 'main'
            - name: Use Node.js
              uses: actions/setup-node@v1
              with:
                node-version: '12.x'
            - name: Run app
              run: npm install
            - run: node main.js
              env:
                JD_COOKIE: ${{ secrets.JD_COOKIE }}
                JD_COOKIE_2: ${{ secrets.JD_COOKIE_2 }} 
                PUSH_KEY: ${{ secrets.PUSH_KEY }}